name: Maven Package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    name: ${{ github.ref_name }}_${{ github.run_id }}_${{ steps.date.outputs.date }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
    # Your build steps here
    - name: Build
      run: echo "Building the project"

    # Your deploy steps here
    - name: Deploy
      run: echo "Deploying the project"
