name: Maven Package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    name: ${{ github.ref_name }}_${{ github.run_id }}
    # env:
    #   REPO_NAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%d%m%Y')" >> $GITHUB_ENV

    - name: print_date
      run: echo $date

    - name: Set ENV variables
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

    - name: Print_reponame
      run: echo $REPO_NAME
      
    # Your build steps here
    - name: Build
      run: echo "Building the project"

    # Your deploy steps here
    - name: Deploy
      run: echo "Deploying the project"
